import {
  Avatar,
  Button,
  Flex,
  Menu,
  MenuButton,
  MenuItem,
  MenuList,
  Modal,
  ModalBody,
  ModalCloseButton,
  ModalContent,
  ModalHeader,
  ModalOverlay,
  Switch,
  Tab,
  TabList,
  TabPanel,
  TabPanels,
  Tabs,
  Text,
  WrapItem,
  useColorMode,
  useDisclosure,
} from "@chakra-ui/react"
import LoginForm from "@/components/LoginForm"
import RegisterForm from "@/components/RegisterForm"
import { useAuth } from "@/helpers/pocketbase"
import { useContext, useState } from "react"
import { UserContext } from "@/pages/_app"
import Head from "next/head"
import Link from "next/link"

export default function Layout(props: {
  children: React.ReactNode
  title?: string
}) {
  const currentUser = useContext(UserContext)
  const { logout } = useAuth()
  const { isOpen, onOpen, onClose } = useDisclosure()
  const { colorMode, toggleColorMode } = useColorMode()

  const authProps = {
    onClose,
  }
  return (
    <>
      <Head>
        <title>{props.title ? props.title : "AI Project Creator POC"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex minW="100vw" minH="100vh" direction="column" alignItems="center">
        <Flex
          as="nav"
          justifyContent="space-around"
          alignItems="center"
          minW="100vw"
          pb={4}
        >
          <Flex alignItems="center">
            <Text as={Link} href="/" fontWeight="bold">
              AI Project Creator POC
            </Text>

            <Text as={Link} href="/about" ml={8}>
              About
            </Text>
          </Flex>
          {currentUser ? (
            <WrapItem>
              <Menu>
                <MenuButton>
                  <Avatar
                    size="md"
                    name={currentUser?.username}
                    src={`https://pocketcreator.jimmymcbride.dev/api/files/_pb_users_auth_/ooelbyidysr4c9n/${currentUser?.avatar}`}
                  />
                </MenuButton>
                <MenuList>
                  <MenuItem onClick={logout}>Logout</MenuItem>
                </MenuList>
              </Menu>
            </WrapItem>
          ) : (
            <div>
              <Button onClick={onOpen}>Login Or Sign Up!</Button>
            </div>
          )}
        </Flex>
        <Modal isOpen={isOpen} onClose={onClose} isCentered>
          <ModalOverlay />
          <ModalContent>
            <ModalHeader textAlign="center">Welcome!</ModalHeader>
            <ModalCloseButton />
            <ModalBody>
              <Tabs isFitted>
                <TabList>
                  <Tab>Login</Tab>
                  <Tab>Sign Up</Tab>
                </TabList>

                <TabPanels>
                  <TabPanel>
                    <LoginForm {...authProps} />
                  </TabPanel>
                  <TabPanel>
                    <RegisterForm {...authProps} />
                  </TabPanel>
                </TabPanels>
              </Tabs>
            </ModalBody>
          </ModalContent>
        </Modal>
        {props.children}
      </Flex>
    </>
  )
}
